In [29]:
import numpy as np
a= np.array([1,2,3,4])
print(a)
print(np.log(a))
print(np.abs(a))
print(np.maximum(a,3))  #逐位比较，取其大着
print(a**2)
print(1/a)

[1 2 3 4]
[ 0.          0.69314718  1.09861229  1.38629436]
[1 2 3 4]
[3 3 3 4]
[ 1  4  9 16]
[ 1.          0.5         0.33333333  0.25      ]


In [18]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(str(1000*(toc-tic)) + "ms")

tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(str(1000*(toc-tic)) + "ms")

3.000020980834961ms
524.0299701690674ms


In [63]:
b = np.array([[1,2,3,5],[1,1,1,1]])
# print(b)
# print(b.T)
c = np.array([[1],[2]])
d = c.T
e = np.array([[1,2]])
print(e.T)

[[1]
 [2]]


In [66]:
a = np.array([1,2,3,4])
b = a.reshape(1,4)
print(b)

[[1 2 3 4]]
